# Generated by Django 4.1.7 on 2023-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=8)),
                ('timestamp', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
